DROP TABLE player;
CREATE TABLE player(
   name      VARCHAR(24) NOT NULL PRIMARY KEY
  ,role      VARCHAR(13) NOT NULL
  ,team_name VARCHAR(4) NOT NULL
  ,amount    INTEGER  NOT NULL
);
INSERT INTO player(name,role,team_name,amount) VALUES ('Rohit Sharma (R)','Batsman','MI',150000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Anmolpreet Singh (R)','Batsman','MI',8000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Ankul Roy (R)','Batsman','MI',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Sherfane Rutherford (R)','Batsman','MI',20000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Suryakumar Yadav (R)','Batsman','MI',32000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Chris Lynn','Batsman','MI',20000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Saurabh Tiwary','Batsman','MI',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Aditya Tare (R)','Wicket Keeper','MI',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Ishan Kishan (R)','Wicket Keeper','MI',62000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Quinton de Kock (R)','Wicket Keeper','MI',28000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Hardik Pandya (R)','All-Rounder','MI',110000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Kieron Pollard (R)','All-Rounder','MI',54000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Krunal Pandya (R)','All-Rounder','MI',88000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Rahul Chahar (R)','All-Rounder','MI',19000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Digvijay Deshmukh','All-Rounder','MI',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Prince Balwant Rai Singh','All-Rounder','MI',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Dhawal Kulkarni (R)','Bowler','MI',7500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Jasprit Bumrah (R)','Bowler','MI',70000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Jayant Yadav (R)','Bowler','MI',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Lasith Malinga (R)','Bowler','MI',20000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Mitchell McClenaghan (R)','Bowler','MI',10000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Trent Boult (R)','Bowler','MI',32000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Nathan Coulter-Nile','Bowler','MI',80000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Mohsin Khan','Bowler','MI',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shreyas Iyer (R)','Batsman','DC',70000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Ajinkya Rahane (R)','Batsman','DC',52500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Avesh Khan (R)','Batsman','DC',7000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Keemo Paul (R)','Batsman','DC',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Prithvi Shaw (R)','Batsman','DC',12000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shikhar Dhawan (R)','Batsman','DC',52000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shimron Heymyer','Batsman','DC',77500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Jason Roy','Batsman','DC',15000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Rishabh Pant (R)','Wicket Keeper','DC',150000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Alex Carey','Wicket Keeper','DC',24000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Marcus Stoinis','All-Rounder','DC',48000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Lalit Yadav','All-Rounder','DC',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Chris Woakes','All-Rounder','DC',15000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Ravichandran Ashwin (R)','Bowler','DC',76000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Sandeep Lamichhane (R)','Bowler','DC',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Axax Patel (R)','Bowler','DC',50000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Harshal Patel (R)','Bowler','DC',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Ishant Sharma (R)','Bowler','DC',11000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Kagiso Rabada (R)','Bowler','DC',42000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Mohit Sharma','Bowler','DC',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Tushar Deshpande','Bowler','DC',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Amit Mishra (R)','Bowler','DC',40000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Karun Nair (R)','Batsman','KXIP',56000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Arshdeep Singh (R)','Batsman','KXIP',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Chris Gayle (R)','Batsman','KXIP',20000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Darshan Nalkande (R)','Batsman','KXIP',3000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Gowtham Krishnappa (R)','Batsman','KXIP',62000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Hardus Viljoen (R)','Batsman','KXIP',7500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Harpreet Brar (R)','Batsman','KXIP',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Mayank Agarwal (R)','Batsman','KXIP',10000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Nicholas Pooran (R)','Batsman','KXIP',42000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Sarfaraz Khan (R)','Batsman','KXIP',2500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Prabhsimran Singh','Wicket Keeper','KXIP',5500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('KL Rahul (R)','Wicket Keeper','KXIP',110000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Mandeep Singh (R)','All-Rounder','KXIP',14000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Glenn Maxwell','All-Rounder','KXIP',107500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Chris Jordan','All-Rounder','KXIP',30000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Deepak Hooda','All-Rounder','KXIP',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('James Neesham','All-Rounder','KXIP',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Tajinder Dhillon','All-Rounder','KXIP',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Ishan Patel','Bowler','KXIP',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Jagadeesha Suchith (R)','Bowler','KXIP',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Mohammad Shami (R)','Bowler','KXIP',48000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Ravi Bishnoi','Bowler','KXIP',20000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Sheldon Cottrell','Bowler','KXIP',85000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Murugan Ashwin (R)','Bowler','KXIP',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Andre Russell (R)','Batsman','KKR',85000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Harry Gurney (R)','Batsman','KKR',7500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Kamlesh Nagarkoti (R)','Batsman','KKR',32000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Lockie Ferguson (R)','Batsman','KKR',16000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Nitish Rana (R)','Batsman','KKR',34000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Prasidh Krishna (R)','Batsman','KKR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Rinku Singh (R)','Batsman','KKR',8000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shubham Gill (R)','Batsman','KKR',18000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Siddhesh Lad (R)','Batsman','KKR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Eoin Morgan','Batsman','KKR',52500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Tom Banton','Batsman','KKR',10000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Rahul Tripathi','Batsman','KKR',6000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Dinesh Karthik (R)','Wicket Keeper','KKR',74000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Nikhil Shankar Naik','Wicket Keeper','KKR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Sunil Narine (R)','All-Rounder','KKR',125000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Pat Cummins','All-Rounder','KKR',155000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shivam Mavi (R)','All-Rounder','KKR',30000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Varun Chakaravarthy','All-Rounder','KKR',40000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Chris Green','All-Rounder','KKR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Kuldeep Yadav (R)','Bowler','KKR',58000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Sandeep Warrier (R)','Bowler','KKR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Pravin Tambe','Bowler','KKR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('M Siddharth','Bowler','KKR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Riyan Parag (R)','Batsman','RR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shashank Singh (R)','Batsman','RR',3000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Steve Smith (R)','Batsman','RR',125000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Robin Uthappa','Batsman','RR',30000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('David Miller','Batsman','RR',7500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Manan Vohra (R)','Batsman','RR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Jos Butler (R)','Wicket Keeper','RR',44000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Sanju Samson (R)','Wicket Keeper','RR',80000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Anuj Rawat','Wicket Keeper','RR',8000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Ben Stokes (R)','All-Rounder','RR',125000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Mahipal Lmoror (R)','All-Rounder','RR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shreyas Gopal (R)','All-Rounder','RR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Yashasvi Jaiswal','All-Rounder','RR',24000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Tom Curran','All-Rounder','RR',10000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Ankit Rajpoot (R)','Bowler','RR',30000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Jofra Archer (R)','Bowler','RR',72000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Mayank Markande (R)','Bowler','RR',20000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Rahul Tweatia (R)','Bowler','RR',30000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Varun Aaron (R)','Bowler','RR',24000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Jaydev Unadkat','Bowler','RR',30000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Kartik Tyagi','Bowler','RR',13000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Andrew Tye','Bowler','RR',10000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Oshane Thomas','Bowler','RR',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Anirudha Ashok Joshi','All-Rounder','RR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Akash Singh','Bowler','RR',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Virat Kohli (R)','Batsman','RCB',170000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('AB de Villiers (R)','Batsman','RCB',110000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Devdutt Padikkal (R)','Batsman','RCB',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Gurkeerat Singh (R)','Batsman','RCB',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Aaron Finch','Batsman','RCB',44000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shahbaz Ahamad','Wicket Keeper','RCB',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Joshua Philippe','Wicket Keeper','RCB',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Pathiv Patel (R)','Wicket Keeper','RCB',17000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Pawan Negi (R)','All-Rounder','RCB',10000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shivam Dube (R)','All-Rounder','RCB',50000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Moeen Ali (R)','All-Rounder','RCB',17000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Isuru Udana','All-Rounder','RCB',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Pavan Deshpande','All-Rounder','RCB',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Christopher Morris','All-Rounder','RCB',100000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Kane Richardson','Bowler','RCB',40000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Dale Steyn','Bowler','RCB',20000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Mohammaed Siraj (R)','Bowler','RCB',26000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Navdeep Saini (R)','Bowler','RCB',30000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Umesh Yadav (R)','Bowler','RCB',42000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Washington Sundar (R)','Bowler','RCB',32000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Yuzvendra Chahal (R)','Bowler','RCB',60000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Kane Williamson','Batsman','SRH',30000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Abhishek Sharma (R)','Batsman','SRH',5500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('David Warner (R)','Batsman','SRH',125000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Manish Pandey (R)','Batsman','SRH',110000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Priyam Garg','Batsman','SRH',19000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Virat Singh','Batsman','SRH',19000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Jonny Bairstow (R)','Wicket Keeper','SRH',22000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shreevats Goswami (R)','Wicket Keeper','SRH',10000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Wridhhiman Saha (R)','Wicket Keeper','SRH',12000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Vijay Shankar (R)','All-Rounder','SRH',32000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Mitchell Marsh','All-Rounder','SRH',20000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Mohammad Nabi (R)','All-Rounder','SRH',10000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Fabian Allen','All-Rounder','SRH',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Sandeep Bavanaka','All-Rounder','SRH',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Sanjay Yadav','All-Rounder','SRH',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Abdul Samad','All-Rounder','SRH',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Basil Thampi (R)','Bowler','SRH',9500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Bhuvneshwar Kumar (R)','Bowler','SRH',85000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Billy Stanlake (R)','Bowler','SRH',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Rashid Khan (R)','Bowler','SRH',90000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Sandeep Sharma (R)','Bowler','SRH',30000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shahbaz Nadeem (R)','Bowler','SRH',32000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Siddarth Kaul (R)','Bowler','SRH',38000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Syed Khaleel Ahmed (R)','Bowler','SRH',30000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('T Natarajan (R)','Bowler','SRH',4000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Ambati Rayadu (R)','Batsman','CSK',22000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Monu Singh (R)','Batsman','CSK',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Murali Vijay (R)','Batsman','CSK',20000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Ruturaj Gaikwad (R)','Batsman','CSK',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Suresh Raine (R)','Batsman','CSK',110000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('MS Dhoni (R)','Wicket Keeper','CSK',150000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Jagadeesan Narayan (R)','Wicket Keeper','CSK',2000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Asif K M (R)','All-Rounder','CSK',4000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Dwayne Bravo (R)','All-Rounder','CSK',64000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Faf du Plessis (R)','All-Rounder','CSK',16000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Karn Sharma (R)','All-Rounder','CSK',50000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Kedar Jadhav (R)','All-Rounder','CSK',78000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Ravindra jadeja (R)','All-Rounder','CSK',70000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shane Watson (R)','All-Rounder','CSK',40000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Sam Curran','All-Rounder','CSK',55000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Deepak Chahar (R)','Bowler','CSK',8000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Harbhajan Singh (R)','Bowler','CSK',20000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Imran Tahir (R)','Bowler','CSK',10000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Lungisani Ngidi (R)','Bowler','CSK',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Mitchell Santner (R)','Bowler','CSK',5000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Shardul Thakur (R)','Bowler','CSK',26000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Piyush Chawla','Bowler','CSK',67500000);
INSERT INTO player(name,role,team_name,amount) VALUES ('Josh Hazlewood','Bowler','CSK',20000000);
INSERT INTO player(name,role,team_name,amount) VALUES ('R. Sai Kishore','Bowler','CSK',2000000);
